server:
  port: 4000
  base_path:
  timeouts:
    read: 10s
    write: 10s 
    shutdown: 10s 
    read_header: 10s
generator:
  convert_url: http://localhost:3000/forms/chromium/convert/html
  merge_url: 
  timeout: 5s
  template: index.html
file_server:
  url_prefix: 